let arr = new Array();
console.log(arr.length);
var arr1 = new Array();
console.log(arr1.length);
let arr3 = new Array(10);
console.log(arr3.length);
arr3.push(1000);
arr3[5] = 100;
console.log(arr3);
let arr4 = new Array(1,2,3,4,5,6,{},true,undefined, null,100);
console.log(arr4);